variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Xmx1024m"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PWD"

compile:
  stage: build
  tags:
    - mvn
    - izar@mobile
  script:
    - 'mvn $MAVEN_CLI_OPTS -U test-compile'

test-master:
  stage: test 
  tags:
    - mvn
    - izar@mobile
  coverage: /^Total coverage. (\d+\.\d+)%/
  script:
    - 'git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"'
    - 'mvn $MAVEN_CLI_OPTS -U clean deploy site:site site:stage -T 1C'
    - '/bin/bash ./calculate-coverage.sh'
    - 'mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.issuesReport.console.enable=true'
    - '. fetch-sonar-result.sh'
  artifacts:
    expire_in: 1 week
    paths:
    - sonar-report.xml
    - "*/target/*.jar"
  only:
    - master
    - dm-master
  except:
    - tags

test:
  stage: test 
  tags:
    - mvn
    - izar@mobile
  coverage: /^Total coverage. (\d+\.\d+)%/
  script:
    - 'git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"'
    - 'mvn $MAVEN_CLI_OPTS -U clean deploy site:site site:stage -T 1C'
    - '/bin/bash ./calculate-coverage.sh'
    - 'mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.branch.name=$(git rev-parse --abbrev-ref HEAD) -Dsonar.issuesReport.console.enable=true'
    - '. fetch-sonar-result.sh'
  artifacts:
    expire_in: 1 week
    paths:
    - sonar-report.xml
    - "*/target/*.jar"
  except:
    - master
    - dm-master
    - tags

release:
  stage: test 
  tags:
    - mvn
    - izar@mobile
  coverage: /^Total coverage. (\d+\.\d+)%/
  script:
    - 'mvn $MAVEN_CLI_OPTS -U clean deploy site:site site:stage -T 1C'
    - '/bin/bash ./calculate-coverage.sh'
    - 'mvn $MAVEN_CLI_OPTS sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.issuesReport.console.enable=true'
    - '. fetch-sonar-result.sh'
  artifacts:
    expire_in: 3 yrs
    paths:
    - sonar-report.xml
    - "*/target/*.jar"
  only:
    - tags
    